// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: pb/demo.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// empty request
type EmptyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_demo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_demo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_pb_demo_proto_rawDescGZIP(), []int{0}
}

// request message
type DemoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DemoRequest) Reset() {
	*x = DemoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_demo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoRequest) ProtoMessage() {}

func (x *DemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_demo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoRequest.ProtoReflect.Descriptor instead.
func (*DemoRequest) Descriptor() ([]byte, []int) {
	return file_pb_demo_proto_rawDescGZIP(), []int{1}
}

func (x *DemoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// reqponse meesage
type DemoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DemoReply) Reset() {
	*x = DemoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_demo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DemoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoReply) ProtoMessage() {}

func (x *DemoReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_demo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoReply.ProtoReflect.Descriptor instead.
func (*DemoReply) Descriptor() ([]byte, []int) {
	return file_pb_demo_proto_rawDescGZIP(), []int{2}
}

func (x *DemoReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_demo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pb_demo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pb_demo_proto_rawDescGZIP(), []int{3}
}

type AnimalId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AnimalId) Reset() {
	*x = AnimalId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_demo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnimalId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimalId) ProtoMessage() {}

func (x *AnimalId) ProtoReflect() protoreflect.Message {
	mi := &file_pb_demo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimalId.ProtoReflect.Descriptor instead.
func (*AnimalId) Descriptor() ([]byte, []int) {
	return file_pb_demo_proto_rawDescGZIP(), []int{4}
}

func (x *AnimalId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Animal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name     string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Height   int32    `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Weight   int32    `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`
	Region   []string `protobuf:"bytes,5,rep,name=region,proto3" json:"region,omitempty"`
	IsCattle bool     `protobuf:"varint,15,opt,name=isCattle,proto3" json:"isCattle,omitempty"`
}

func (x *Animal) Reset() {
	*x = Animal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_demo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Animal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Animal) ProtoMessage() {}

func (x *Animal) ProtoReflect() protoreflect.Message {
	mi := &file_pb_demo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Animal.ProtoReflect.Descriptor instead.
func (*Animal) Descriptor() ([]byte, []int) {
	return file_pb_demo_proto_rawDescGZIP(), []int{5}
}

func (x *Animal) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Animal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Animal) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Animal) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Animal) GetRegion() []string {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *Animal) GetIsCattle() bool {
	if x != nil {
		return x.IsCattle
	}
	return false
}

type AnimalInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	//  Animal animal = 2;
	Type     string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name     string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Height   int32    `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Weight   int32    `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Region   []string `protobuf:"bytes,6,rep,name=region,proto3" json:"region,omitempty"`
	IsCattle bool     `protobuf:"varint,15,opt,name=isCattle,proto3" json:"isCattle,omitempty"`
}

func (x *AnimalInfo) Reset() {
	*x = AnimalInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_demo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnimalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimalInfo) ProtoMessage() {}

func (x *AnimalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_demo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimalInfo.ProtoReflect.Descriptor instead.
func (*AnimalInfo) Descriptor() ([]byte, []int) {
	return file_pb_demo_proto_rawDescGZIP(), []int{6}
}

func (x *AnimalInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AnimalInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AnimalInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AnimalInfo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *AnimalInfo) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *AnimalInfo) GetRegion() []string {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *AnimalInfo) GetIsCattle() bool {
	if x != nil {
		return x.IsCattle
	}
	return false
}

type Animals struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Animals []*AnimalInfo `protobuf:"bytes,1,rep,name=animals,proto3" json:"animals,omitempty"`
}

func (x *Animals) Reset() {
	*x = Animals{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_demo_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Animals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Animals) ProtoMessage() {}

func (x *Animals) ProtoReflect() protoreflect.Message {
	mi := &file_pb_demo_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Animals.ProtoReflect.Descriptor instead.
func (*Animals) Descriptor() ([]byte, []int) {
	return file_pb_demo_proto_rawDescGZIP(), []int{7}
}

func (x *Animals) GetAnimals() []*AnimalInfo {
	if x != nil {
		return x.Animals
	}
	return nil
}

var File_pb_demo_proto protoreflect.FileDescriptor

var file_pb_demo_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x62, 0x2f, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0x0e, 0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x21, 0x0a, 0x0b, 0x44, 0x65, 0x6d, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x25, 0x0a, 0x09, 0x44, 0x65, 0x6d, 0x6f, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x07, 0x0a,
	0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x1a, 0x0a, 0x08, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c,
	0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x94, 0x01, 0x0a, 0x06, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x77,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a,
	0x08, 0x69, 0x73, 0x43, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x69, 0x73, 0x43, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x22, 0xa8, 0x01, 0x0a, 0x0a, 0x41, 0x6e,
	0x69, 0x6d, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x43, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x43, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x22, 0x33, 0x0a, 0x07, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x12,
	0x28, 0x0a, 0x07, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x07, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x32, 0x3d, 0x0a, 0x04, 0x44, 0x65, 0x6d,
	0x6f, 0x12, 0x35, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6d, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6d,
	0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x32, 0xbe, 0x01, 0x0a, 0x0d, 0x41, 0x6e, 0x69,
	0x6d, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2b, 0x0a, 0x09, 0x47, 0x65,
	0x74, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x12, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x6e, 0x69,
	0x6d, 0x61, 0x6c, 0x49, 0x64, 0x1a, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x61,
	0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x27, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x41,
	0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x12, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x22, 0x00,
	0x12, 0x2c, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c,
	0x12, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x1a, 0x0e, 0x2e, 0x70,
	0x62, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x29,
	0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x12, 0x0c,
	0x2e, 0x70, 0x62, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x49, 0x64, 0x1a, 0x09, 0x2e, 0x70,
	0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_pb_demo_proto_rawDescOnce sync.Once
	file_pb_demo_proto_rawDescData = file_pb_demo_proto_rawDesc
)

func file_pb_demo_proto_rawDescGZIP() []byte {
	file_pb_demo_proto_rawDescOnce.Do(func() {
		file_pb_demo_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_demo_proto_rawDescData)
	})
	return file_pb_demo_proto_rawDescData
}

var file_pb_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pb_demo_proto_goTypes = []interface{}{
	(*EmptyRequest)(nil), // 0: pb.EmptyRequest
	(*DemoRequest)(nil),  // 1: pb.DemoRequest
	(*DemoReply)(nil),    // 2: pb.DemoReply
	(*Empty)(nil),        // 3: pb.Empty
	(*AnimalId)(nil),     // 4: pb.AnimalId
	(*Animal)(nil),       // 5: pb.Animal
	(*AnimalInfo)(nil),   // 6: pb.AnimalInfo
	(*Animals)(nil),      // 7: pb.Animals
}
var file_pb_demo_proto_depIdxs = []int32{
	6, // 0: pb.Animals.animals:type_name -> pb.AnimalInfo
	1, // 1: pb.Demo.GetMessageService:input_type -> pb.DemoRequest
	4, // 2: pb.AnimalService.GetAnimal:input_type -> pb.AnimalId
	3, // 3: pb.AnimalService.ListAnimals:input_type -> pb.Empty
	5, // 4: pb.AnimalService.CreateAnimal:input_type -> pb.Animal
	4, // 5: pb.AnimalService.DeleteAnimal:input_type -> pb.AnimalId
	2, // 6: pb.Demo.GetMessageService:output_type -> pb.DemoReply
	6, // 7: pb.AnimalService.GetAnimal:output_type -> pb.AnimalInfo
	7, // 8: pb.AnimalService.ListAnimals:output_type -> pb.Animals
	6, // 9: pb.AnimalService.CreateAnimal:output_type -> pb.AnimalInfo
	3, // 10: pb.AnimalService.DeleteAnimal:output_type -> pb.Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_demo_proto_init() }
func file_pb_demo_proto_init() {
	if File_pb_demo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_demo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_demo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DemoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_demo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DemoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_demo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_demo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnimalId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_demo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Animal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_demo_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnimalInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_demo_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Animals); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_demo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pb_demo_proto_goTypes,
		DependencyIndexes: file_pb_demo_proto_depIdxs,
		MessageInfos:      file_pb_demo_proto_msgTypes,
	}.Build()
	File_pb_demo_proto = out.File
	file_pb_demo_proto_rawDesc = nil
	file_pb_demo_proto_goTypes = nil
	file_pb_demo_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DemoClient is the client API for Demo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DemoClient interface {
	// request demo message
	GetMessageService(ctx context.Context, in *DemoRequest, opts ...grpc.CallOption) (*DemoReply, error)
}

type demoClient struct {
	cc grpc.ClientConnInterface
}

func NewDemoClient(cc grpc.ClientConnInterface) DemoClient {
	return &demoClient{cc}
}

func (c *demoClient) GetMessageService(ctx context.Context, in *DemoRequest, opts ...grpc.CallOption) (*DemoReply, error) {
	out := new(DemoReply)
	err := c.cc.Invoke(ctx, "/pb.Demo/GetMessageService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DemoServer is the server API for Demo service.
type DemoServer interface {
	// request demo message
	GetMessageService(context.Context, *DemoRequest) (*DemoReply, error)
}

// UnimplementedDemoServer can be embedded to have forward compatible implementations.
type UnimplementedDemoServer struct {
}

func (*UnimplementedDemoServer) GetMessageService(context.Context, *DemoRequest) (*DemoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessageService not implemented")
}

func RegisterDemoServer(s *grpc.Server, srv DemoServer) {
	s.RegisterService(&_Demo_serviceDesc, srv)
}

func _Demo_GetMessageService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DemoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoServer).GetMessageService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Demo/GetMessageService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoServer).GetMessageService(ctx, req.(*DemoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Demo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Demo",
	HandlerType: (*DemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMessageService",
			Handler:    _Demo_GetMessageService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/demo.proto",
}

// AnimalServiceClient is the client API for AnimalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AnimalServiceClient interface {
	GetAnimal(ctx context.Context, in *AnimalId, opts ...grpc.CallOption) (*AnimalInfo, error)
	ListAnimals(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Animals, error)
	CreateAnimal(ctx context.Context, in *Animal, opts ...grpc.CallOption) (*AnimalInfo, error)
	DeleteAnimal(ctx context.Context, in *AnimalId, opts ...grpc.CallOption) (*Empty, error)
}

type animalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnimalServiceClient(cc grpc.ClientConnInterface) AnimalServiceClient {
	return &animalServiceClient{cc}
}

func (c *animalServiceClient) GetAnimal(ctx context.Context, in *AnimalId, opts ...grpc.CallOption) (*AnimalInfo, error) {
	out := new(AnimalInfo)
	err := c.cc.Invoke(ctx, "/pb.AnimalService/GetAnimal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *animalServiceClient) ListAnimals(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Animals, error) {
	out := new(Animals)
	err := c.cc.Invoke(ctx, "/pb.AnimalService/ListAnimals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *animalServiceClient) CreateAnimal(ctx context.Context, in *Animal, opts ...grpc.CallOption) (*AnimalInfo, error) {
	out := new(AnimalInfo)
	err := c.cc.Invoke(ctx, "/pb.AnimalService/CreateAnimal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *animalServiceClient) DeleteAnimal(ctx context.Context, in *AnimalId, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.AnimalService/DeleteAnimal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnimalServiceServer is the server API for AnimalService service.
type AnimalServiceServer interface {
	GetAnimal(context.Context, *AnimalId) (*AnimalInfo, error)
	ListAnimals(context.Context, *Empty) (*Animals, error)
	CreateAnimal(context.Context, *Animal) (*AnimalInfo, error)
	DeleteAnimal(context.Context, *AnimalId) (*Empty, error)
}

// UnimplementedAnimalServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAnimalServiceServer struct {
}

func (*UnimplementedAnimalServiceServer) GetAnimal(context.Context, *AnimalId) (*AnimalInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnimal not implemented")
}
func (*UnimplementedAnimalServiceServer) ListAnimals(context.Context, *Empty) (*Animals, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAnimals not implemented")
}
func (*UnimplementedAnimalServiceServer) CreateAnimal(context.Context, *Animal) (*AnimalInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAnimal not implemented")
}
func (*UnimplementedAnimalServiceServer) DeleteAnimal(context.Context, *AnimalId) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAnimal not implemented")
}

func RegisterAnimalServiceServer(s *grpc.Server, srv AnimalServiceServer) {
	s.RegisterService(&_AnimalService_serviceDesc, srv)
}

func _AnimalService_GetAnimal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnimalId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnimalServiceServer).GetAnimal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AnimalService/GetAnimal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnimalServiceServer).GetAnimal(ctx, req.(*AnimalId))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnimalService_ListAnimals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnimalServiceServer).ListAnimals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AnimalService/ListAnimals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnimalServiceServer).ListAnimals(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnimalService_CreateAnimal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Animal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnimalServiceServer).CreateAnimal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AnimalService/CreateAnimal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnimalServiceServer).CreateAnimal(ctx, req.(*Animal))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnimalService_DeleteAnimal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnimalId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnimalServiceServer).DeleteAnimal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AnimalService/DeleteAnimal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnimalServiceServer).DeleteAnimal(ctx, req.(*AnimalId))
	}
	return interceptor(ctx, in, info, handler)
}

var _AnimalService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AnimalService",
	HandlerType: (*AnimalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAnimal",
			Handler:    _AnimalService_GetAnimal_Handler,
		},
		{
			MethodName: "ListAnimals",
			Handler:    _AnimalService_ListAnimals_Handler,
		},
		{
			MethodName: "CreateAnimal",
			Handler:    _AnimalService_CreateAnimal_Handler,
		},
		{
			MethodName: "DeleteAnimal",
			Handler:    _AnimalService_DeleteAnimal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/demo.proto",
}
